---
title: "1 - Feature Engineering - Classwork"
subtitle: "Advanced tidymodels"
editor_options: 
  chunk_output_type: console
---

We recommend restarting R between each slide deck!

## Hotel data

```{r}
library(tidymodels)

# Max's usual settings: 
tidymodels_prefer()
theme_set(theme_bw())
options(
  pillar.advice = FALSE, 
  pillar.min_title_chars = Inf
)

data(hotel_rates)
set.seed(295)
hotel_rates <- 
  hotel_rates %>% 
  sample_n(5000) %>% 
  arrange(arrival_date) %>% 
  select(-arrival_date) %>% 
  mutate(
    company = factor(as.character(company)),
    country = factor(as.character(country)),
    agent = factor(as.character(agent))
  )
```

## Data spending

```{r}
set.seed(4028)
hotel_split <-
  initial_split(hotel_rates, strata = avg_price_per_room)

hotel_train <- training(hotel_split)
hotel_test <- testing(hotel_split)
```

## Your turn

Let's take some time and investigate the _training data_. The outcome is `avg_price_per_room`. 

Are there any interesting characteristics of the data?

```{r}
# Your code here!
glimpse(hotel_train)

library(skimr)
skim(hotel_train)

hotel_train |> 
  summarise(Count = n(), .by = meal) |> 
  arrange(-Count)

hotel_train |> 
  ggplot(aes(avg_price_per_room)) + 
  geom_histogram()

hotel_train |> 
  ggplot(aes(arrival_date_num, avg_price_per_room)) + 
  geom_point(alpha = 0.1) +
  geom_smooth()

summary_by_room_type <- hotel_train |> 
  mutate(year = stringr::str_sub(arrival_date_num, 1, 4)) |> 
  summarise(count = n(),
            avg_price = mean(avg_price_per_room, na.rm = T),
            lead_time = mean(lead_time, na.rm = T),
            .by = c(meal, year)) |> 
  arrange(meal, year)

summary_by_adults <- hotel_train |> 
  mutate(year = stringr::str_sub(arrival_date_num, 1, 4)) |> 
  summarise(count = n(),
            avg_price = mean(avg_price_per_room, na.rm = T),
            lead_time = mean(lead_time, na.rm = T),
            .by = c(year, adults)) |> 
  arrange(adults, year)

hotel_train |> 
  ggplot(aes(x = avg_price_per_room))

```
